### PR TITLE
Improved Segment#to_array

### PR DESCRIPTION
**Pull request by zedalaye**
so Array#<=> can be used to compare Integer Segments with String Segments

### CODE REVIEW

**Comment by dogweather** [comment]
Hi, I'm sorry about the delay responding, I didn't have my notifications set correctly. Checking it out now.

**Comment by uberjay** [comment]
This fix is working well for me. I ran into this bug a few days ago, and stumbled across this bug/PR at just the right time. Thanks. :)

**Comment by sigra** [comment]
+1 for this PR

**Comment by ompugao** [comment]
+1
nice patch!

**Comment by dogweather** [comment]
Excellent, thank you everyone.

**Comment by dogweather** [comment]
Released new gem version 1.4.0 with this fix.

**Pull request merged**
